/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.*;


/**
 *
 * @author charleswong
 */
public class LoginPage extends javax.swing.JFrame {
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1_TeacherID = new javax.swing.JTextField();
        jTextField2_Password = new javax.swing.JTextField();
        jButton1_SignIN = new javax.swing.JButton();
        jButton3_Register = new javax.swing.JButton();
        jLabel4_Response = new javax.swing.JLabel();
        jLabel5_Response = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("LOGIN PAGE");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Teacher ID");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Password");

        jTextField1_TeacherID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_TeacherIDActionPerformed(evt);
            }
        });

        jButton1_SignIN.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButton1_SignIN.setText("Sign In ");
        jButton1_SignIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_SignINMouseClicked(evt);
            }
        });
        jButton1_SignIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_SignINActionPerformed(evt);
            }
        });

        jButton3_Register.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButton3_Register.setText("Register");
        jButton3_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3_RegisterMouseClicked(evt);
            }
        });
        jButton3_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_RegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5_Response, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4_Response, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jButton1_SignIN, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                            .addComponent(jButton3_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField2_Password)
                                .addComponent(jTextField1_TeacherID, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4_Response, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5_Response, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1_TeacherID, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_SignIN, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_TeacherIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_TeacherIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_TeacherIDActionPerformed

    private void jButton1_SignINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_SignINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_SignINActionPerformed
    
    private void jButton1_SignINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_SignINMouseClicked
        String getTeacherID = jTextField1_TeacherID.getText(); 
        String getPassword = jTextField2_Password.getText();
        
        int equal = 0;
        Connection myCon = null;
        
        System.out.println(getTeacherID);
        System.out.println(getPassword);
        try {
            Connection myCon2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/TeacherInfo", "myuser" , "xxxx");
            Connection myCon3 = DriverManager.getConnection("jdbc:mysql://localhost:3306/TeacherInfo", "myuser" , "xxxx");
            
            Statement myStmt2 = myCon2.createStatement();
            Statement myStmt3 = myCon3.createStatement();
            

            ResultSet myRs2 = myStmt2.executeQuery("select id from Teacher");
            ResultSet myRs3 = myStmt3.executeQuery("select Password from Teacher");
                  
            while (myRs2.next() && myRs3.next()){
                
                String dbTID = myRs2.getString("id");
                String dbpassword = myRs3.getString("Password");
                
                if (getPassword.equals(dbpassword) && getTeacherID.equals(dbTID)){
                    equal = 1;
                    System.out.println("equal");
                }  
            }
            if (equal == 1)                
                {
                
                dispose();
                MainScreen MS = new MainScreen(getTeacherID);
                MS.setVisible(true); 
                
                }
            else{jLabel5_Response.setText("Invalid");}
                   

        } catch (SQLException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1_SignINMouseClicked
    
    
    private void jButton3_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_RegisterMouseClicked
        JTextField field1 = new JTextField();
        JTextField field2 = new JTextField();
        JTextField field3 = new JTextField();
        int tryInt = 0;
        Object[] fields = {
            "Teacher ID", field1,
            "Password", field2,
            "Name", field3
        };
        
        JOptionPane.showConfirmDialog(null,fields,"Register Teacher ID and Password and Name ",JOptionPane.OK_CANCEL_OPTION);
        String TID = field1.getText();
        String PW = field2.getText();
        String Nm = field3.getText();

        
        String Exists = "false";
        PreparedStatement myStmt = null;
        Connection myCon = null;
        ResultSet myRs = null;
        
        try{
             myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/TeacherInfo", "myuser" , "xxxx");
            //create a statement 
            
            Statement myStmt1 = myCon.createStatement();
            //Executen SQL query            
            myRs = myStmt1.executeQuery("select id from Teacher");
            while (myRs.next()){
                if (myRs.getString("id").equals(TID)){
                    Exists = "true";
                    System.out.println("Id already exists");
                }
            }
            
            if ("false".equals(Exists)){    
                
            String sql = "insert into Teacher "
                    + " (id , name)"
                    + " values (?,?)" ;   
            
            myStmt = myCon.prepareStatement("insert into Teacher (id , name , Password) values (?,?,?)");
            
            myStmt.setString(1, TID);
            myStmt.setString(2, Nm);
            myStmt.setString(3, PW);
                       
            
            myStmt.executeUpdate();
            
            jLabel4_Response.setText("Register Sucessed");
            }
            else{jLabel4_Response.setText("Register Unsucessed");}

        }
            
        catch (Exception exc){
        exc.printStackTrace();

        }
        
        
    }//GEN-LAST:event_jButton3_RegisterMouseClicked

    private void jButton3_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_RegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3_RegisterActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_SignIN;
    private javax.swing.JButton jButton3_Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4_Response;
    private javax.swing.JLabel jLabel5_Response;
    private javax.swing.JTextField jTextField1_TeacherID;
    private javax.swing.JTextField jTextField2_Password;
    // End of variables declaration//GEN-END:variables
}
